apiVersion: apps/v1 
kind: Deployment
metadata:
  name: html-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: html-app 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: html-app 
    spec:
      containers:
      - name: html-app
        image: hlesey/html-app:1.0
        resources:
          requests:
            cpu: "10m"
            memory: "10Mi"
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: html-app
spec:
  selector:
    app: html-app
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: html-app
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: html-app
spec:
  gateways:
    - html-app
  hosts:
    - '*'
  http:
    - match:
        - uri:
            exact: /
        - uri:
            exact: /version.html
      route:
        - destination:
            host: html-app