apiVersion: v1
kind: Service
metadata:
  name: html-app
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: html-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: html-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: html-app
    spec:
      containers:
        - image: hlesey/html-app:2.0
          name: html-app
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: html-app
spec:
  gateways:
    - html-app
  hosts:
    - '*'
  http:
    - match:
        - uri:
            exact: /
        - uri:
            exact: /version.html
      route:
        - destination:
            host: html-app
