apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: phippy-admin
  name: phippy-admin
spec:
  selector:
    matchLabels:
      app: phippy-admin
  template:
    metadata:
      labels:
        app: phippy-admin
    spec:
      containers:
      - name: proxy
        image: hlesey/proxy:1.0
        envFrom:
        - configMapRef:
            name: phippy-admin
        ports:
        - name: http-alt
          containerPort: 8080
        resources:
          requests:
            cpu: "20m"
            memory: "10Mi"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: phippy-admin
data:
  PORT: '8080'
  REWRITE_MESSAGE: '{;{"admin_portal":true,'
  REDIRECT_URL: 'http://phippy-api'
---
apiVersion: v1
kind: Service
metadata:
  name: phippy-admin
spec:
  selector:
    app: phippy-admin
  ports:
  - name: http
    port: 80
    targetPort: http-alt
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: phippy-admin
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
   - host: phippy-admin.local
     http:
      paths:
      - path: /
        backend:
          serviceName: phippy-admin
          servicePort: 80