# https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
# https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: my-replicaset
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 10
          type: Utilization
      type: Resource
  minReplicas: 1
  maxReplicas: 10
