apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
  namespace: lab-deployments
  labels:
    app: my-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: nginx
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: my-app
#   namespace: lab-deployments
# spec:
#   selector:
#     app: my-app
#   type: NodePort
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#       nodePort: 30100
#       protocol: TCP
