apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
  labels:
    app: my-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: ghcr.io/hlesey/nginx:1.21.6
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
        ports:
        - name: http
          containerPort: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: my-app
# spec:
#   selector:
#     app: my-app
#   type: NodePort
#   ports:
#     - name: http
#       port: 80
#       targetPort: 80
#       nodePort: 30100
