apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phippy-ui
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: phippy.cluster0.qedzone.ro
    http:
      paths:
      - path: /
        pathType: "Prefix"
        backend:
          service:
            name: phippy-ui
            port:
              name: http
