# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
BOX_IMAGE="ubuntu/bionic64"

required_plugins = %w(vagrant-vbguest vagrant-share)

required_plugins.each do |plugin|
  system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end

  cluster = {
    "controller-0" => { :ip => "10.240.0.10", :cpus => 1, :mem => 1024 },
    "controller-1" => { :ip => "10.240.0.11", :cpus => 1, :mem => 1024 },
    "controller-2" => { :ip => "10.240.0.12", :cpus => 1, :mem => 1024 },

    "worker-0"     => { :ip => "10.240.0.20", :cpus => 1, :mem => 512 },
    "worker-1"     => { :ip => "10.240.0.21", :cpus => 1, :mem => 512 },
    "worker-2"     => { :ip => "10.240.0.22", :cpus => 1, :mem => 512 }
  }
 
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  cluster.each_with_index do |(hostname, info), index|
    config.vm.define hostname do |cfg|
      cfg.vm.provider :virtualbox do |vb, override|
        config.vm.box = BOX_IMAGE
        override.vm.network :private_network, ip: "#{info[:ip]}"
        override.vm.hostname = hostname
        override.vm.provision "shell", path: "src/scripts/setup.sh"
        
        override.vm.synced_folder "../../../", "/repo", id: "repo",
        owner: "vagrant",
        group: "vagrant",
        mount_option: ["dmode=777,fmode=777"]
       
        override.vm.synced_folder "src", "/src", id: "scripts",
        owner: "vagrant",
        group: "vagrant",
        mount_option: ["dmode=777,fmode=777"]

        vb.name = hostname
        vb.customize ["modifyvm", :id, "--memory", info[:mem], "--cpus", info[:cpus], "--hwvirtex", "on"]
      end # end provider
    end # end config

  end # end cluster
end
