apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostnames
spec:
  selector:
    matchLabels:
      app: hostnames
  replicas: 3
  template:
    metadata:
      labels:
        app: hostnames
    spec:
      containers:
      - name: hostnames
        image: k8s.gcr.io/serve_hostname
        command: ["echo THIS LINE IS WRONG"]
        resources:
          limits:
            memory: 4Mi
        ports:
        - containerPort: 9376
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hostnames
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: hostnames.clusterx.qedzone.ro
    http:
      paths:
      - path: /
        pathType: "Prefix" 
        backend:
          service:
            name: hostnames
            port:
              name: http
