apiVersion: v1
kind: Pod
metadata:
  name: msg-path-demo
spec:
  containers:
  - name: msg-path-demo-container
    image: ghcr.io/hlesey/debian:latest
    terminationMessagePath: "/tmp/my-log"
  restartPolicy: Never