apiVersion: v1
kind: Pod
metadata:
  name: pod-config-env
spec:
  containers:
  - name: test-container
    image: ghcr.io/hlesey/nginx:1.21.6
    env:
    - name: LOG_LEVEL
      valueFrom:
        configMapKeyRef:
          name: log-config
          key: log.level
    - name: LOG_LOCATION
      valueFrom:
        configMapKeyRef:
          name: log-config
          key: log.location
