apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-env
spec:
  containers:
  - name: redis
    image: ghcr.io/hlesey/redis:latest
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: dbsecret
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: dbsecret
            key: password