apiVersion: v1
kind: Pod
metadata:
  name: pod-config-vol
spec:
  containers:
  - name: nginx-container
    image: ghcr.io/hlesey/nginx:latest
    volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: log-config
