apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
  namespace: lab-services-load-balancing-and-networking
spec:
  selector:
    app: my-app
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30000
    protocol: TCP