---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: phippy-api
spec:
  rules:
  - host: phippy-api.local
    http:
      paths:
      - path: /
        backend:
          serviceName: phippy-api
          servicePort: 80
