kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-manager
rules:
  - apiGroups: ["apps", "extensions"] # "" indicates the core API group
    resources: ["deployments"]
    verbs: ["get", "watch", "list", "create", "delete"]