kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-manager
rules:
  - apiGroups: ["", "apps"] # "" indicates the core API group
    resources: ["deployments", "replicasets", "pods"]
    verbs: ["*"]
