apiVersion: v1
kind: LimitRange
metadata:
  name: lr-compute
spec:
  limits:
  - default:
      cpu: "1"
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container
