apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaller
  namespace: lab-replicaset-and-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: my-replicaset
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50