apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: qedzone/alpine-curl 
        # command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
        command: [ "/usr/bin/curl", "-s", "http://ipecho.net/plain" ] 
      restartPolicy: Never
  backoffLimit: 4