apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolbox
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: debug
    spec:
      containers:
      - name: toolbox
        image: hlesey/toolbox
