apiVersion: v1
kind: Pod
metadata:
  name: test-emptydir
spec:
  containers:
  - name: test-emptydir
    image: k8s.gcr.io/test-webserver
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}