apiVersion: v1
kind: Pod
metadata:
  name: seccomp-pod
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: app
    image: busybox:1.28
    command: ["sh", "-c", "echo 'Seccomp active!' && sleep 1h"]
