---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: phippy-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: phippy
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: phippy
        app.kubernetes.io/component: api
    spec:
      containers:
      - name: phippy
        image: ghcr.io/hlesey/phippy-api:<WRONG VERSION>
        env:
        - name: DB_PORT
          value: "6379"
        - name: DB_HOST
          value: "phippy-db"
        resources:
          limits:
            memory: 4Mi
        ports:
        - name: http
          containerPort: 5000
        readinessProbe:
          httpGet:
            path: /readyzz
            port: http
---
apiVersion: v1
kind: Service
metadata:
  name: phippy-api
spec:
  selector:
    app.kubernetes.io/name: phippy
    app.kubernetes.io/compnoent: api
  ports:
  - name: http
    port: 80
    targetPort: 5001
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: phippy-api
spec:
  parentRefs:
  - name: eg
    namespace: envoy-gateway
  hostnames:
  - phippy-api.clusterx.qedzone.ro
  rules:
  - backendRefs:
    - name: phippy-db
      port: 443
    matches:
    - path:
        type: PathPrefix
        value: /
