apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
  namespace: lab-pss
spec:
  containers:
  - name: app
    image: busybox:1.36
    command: ["sh", "-c", "echo 'Running privileged!' && sleep 1h"]
    securityContext:
      privileged: true
