apiVersion: v1
kind: Namespace
metadata:
 name: ctfd
--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv05
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /nfs/pv05
    server: nfsserver.local
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv06
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /nfs/pv06
    server: nfsserver.local
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle