apiVersion: v1
kind: Pod
metadata:
  name: test-emptydir
spec:
  containers:
  - name: test-emptydir
    image: ghcr.io/hlesey/nginx:1.21.6
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}