apiVersion: v1
kind: Pod
metadata:
  name: test-hostpath
spec:
  containers:
  - name: test-hostpath
    image: ghcr.io/hlesey/nginx:1.21.6
    volumeMounts:
    - name: host-data
      mountPath: /usr/share/nginx/html/index.html
  volumes:
  - name: host-data
    hostPath:
      path: /etc/hostname
