apiVersion: v1
kind: Pod
metadata:
  name: pod-with-persistance
spec:
  containers:
  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: persistence-data
      mountPath: /usr/share/nginx/html/
  volumes:
    - name: persistence-data
      persistentVolumeClaim:
        claimName: pvc00