apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv00
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /nfs/pv00
    server: nfsserver.local
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /nfs/pv01
    server: nfsserver.local
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv02
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /nfs/pv02
    server: nfsserver.local
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv03
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /nfs/pv03
    server: nfsserver.local
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv04
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /nfs/pv04
    server: nfsserver.local
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv05
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /nfs/pv05
    server: nfsserver.local
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv06
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /nfs/pv06
    server: nfsserver.local
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv07
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  storageClassName: ssd
  nfs:
    path: /nfs/pv07
    server: nfsserver.local
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv08
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  storageClassName: slow
  nfs:
    path: /nfs/pv08
    server: nfsserver.local
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
---
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv09
spec:
  capacity:
    storage: 100Ki
  accessModes:
  - ReadWriteMany
  nfs:
    path: /nfs/pv09
    server: nfsserver.local
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle