apiVersion: v1
kind: Pod
metadata:
  name: phippy-db
  labels:
    app.kubernetes.io/name: phippy
    app.kubernetes.io/component: db
spec:
  containers:
    - name: redis
      image: ghcr.io/hlesey/redis:7.4
      ports:
      - name: redis
        containerPort: 6379
