apiVersion: v1
kind: Pod
metadata:
  name: phippy-api
  labels:
    app.kubernetes.io/name: phippy
    app.kubernetes.io/component: api
spec:
  containers:
    - name: phippy-api
      image: ghcr.io/hlesey/phippy-api:1.0
      ports:
        - name: http
          containerPort: 5000
      env:
      - name: DB_HOST
        # value: "10.0.X.X" # modify this with your phippy-db Pod IP
        value: "phippy-db"
      livenessProbe:
        httpGet:
          path: /livez
          port: 5000
      readinessProbe:
        httpGet:
          path: /readyz
          port: 5000
      resources:
        limits:
          memory: "100Mi"
        requests:
          cpu: "100m"
          memory: "100Mi"
