apiVersion: v1
kind: Pod
metadata:
  name: pod-with-healthcheck
  namespace: lab-pods
spec:
  containers:
  - name: nginx
    image: ghcr.io/hlesey/nginx:1.21.6
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 15
    ports:
    - containerPort: 80
