apiVersion: v1
kind: Pod
metadata:
  name: two-containers
  namespace: lab-pods
spec:
  containers:
  - name: debian-container
    image: debian
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["/bin/sh"]
    args: ["-c", "echo Hello from the debian container > /pod-data/index.html"]
  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  restartPolicy: Never
  volumes:
  - name: shared-data
    emptyDir: {}
