apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:
  containers:
  
  - name: content-manager
    image: ghcr.io/hlesey/debian:stable-20231218
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["/bin/sh"]
    args: ["-c", "echo Hello from the debian container > /pod-data/index.html"]

  - name: consumer
    image: ghcr.io/hlesey/nginx:1.25.3
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  
  volumes:
  - name: shared-data
    emptyDir: {}

  restartPolicy: Never
