# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
BOX_IMAGE="ubuntu/bionic64"
BOX_VERSION = "20191115.0.0"

required_plugins = %w(vagrant-vbguest vagrant-share)

required_plugins.each do |plugin|
  system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end

cluster = {
  "lab-master" => { :ip => "192.168.101.100", :cpus => 4, :mem => 2048 },
  "lab-node01" => { :ip => "192.168.101.101", :cpus => 2, :mem => 1024 },
}
 
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  cluster.each_with_index do |(hostname, info), index|
    config.vm.define hostname do |cfg|
      cfg.vm.provider :virtualbox do |vb, override|
        config.vm.box = BOX_IMAGE
        config.vm.box_version = BOX_VERSION
        override.vm.network :private_network, ip: "#{info[:ip]}"
        override.vm.hostname = hostname + ".local"
        override.vm.provision "shell", path: "src/scripts/setup.sh"
        
        override.vm.synced_folder "../", "/repo", id: "repo",
        owner: "vagrant",
        group: "vagrant",
        mount_option: ["dmode=777,fmode=777"]
       
        override.vm.synced_folder "src", "/src", id: "scripts",
        owner: "vagrant",
        group: "vagrant",
        mount_option: ["dmode=777,fmode=777"]

        vb.name = hostname
        vb.customize ["modifyvm", :id, "--memory", info[:mem], 
                      "--cpus", info[:cpus], "--hwvirtex", "on", 
                      "--ioapic", "on", "--uartmode1", "disconnected"]
      end # end provider
    end # end config

  end # end cluster
end