# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
BOX_IMAGE="ubuntu/focal64"
BOX_VERSION="20220308.0.0"

required_plugins = %w(vagrant-vbguest)

# On latest versions of VirtualBox you have to manually allow IP addresses range in /etc/vbox/networks.conf
# See https://www.virtualbox.org/manual/ch06.html#network_hostonly for more details
cluster = {
  "lab-control-plane" => { :ip => "192.168.235.100", :cpus => 4, :mem => 2048 },
  "lab-node" => { :ip => "192.168.235.101", :cpus => 2, :mem => 1024 },
}

required_plugins.each do |plugin|
  system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end
 
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  cluster.each_with_index do |(hostname, info), index|
    config.vm.define hostname do |cfg|
      cfg.vm.provider :virtualbox do |vb, override|
        config.vm.box = BOX_IMAGE
        config.vm.box_version = BOX_VERSION
        override.vm.network :private_network, ip: "#{info[:ip]}"
        override.vm.hostname = hostname + ".local"
        override.vm.provision "shell", path: "src/scripts/setup.sh"
        
        override.vm.synced_folder "../", "/repo", id: "repo",
        owner: "vagrant",
        group: "vagrant",
        mount_option: ["dmode=777,fmode=777"]
       
        override.vm.synced_folder "src", "/src", id: "scripts",
        owner: "vagrant",
        group: "vagrant",
        mount_option: ["dmode=777,fmode=777"]

        vb.name = hostname
        vb.customize [
          "modifyvm", :id, 
          "--memory", info[:mem], 
          "--cpus", info[:cpus],
          "--ioapic", "on",
          "--uartmode1", "file", File.join(Dir.pwd, hostname + "-console.log")
        ]
      end # end provider
    end # end config

  end # end cluster
end