# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
BOX_IMAGE="ubuntu/bionic64"

required_plugins = %w(vagrant-vbguest vagrant-share)

required_plugins.each do |plugin|
  system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048", "--cpus", "2", "--ioapic", "on"]
  end

  config.vm.synced_folder "../", "/repo", id: "repo",
    owner: "vagrant",
    group: "vagrant",
    mount_option: ["dmode=777,fmode=777"]

  config.vm.synced_folder "src", "/src", id: "scripts",
    owner: "vagrant",
    group: "vagrant",
    mount_option: ["dmode=777,fmode=777"]

  # master node
  config.vm.define "master" do |master|
    master.vm.box = BOX_IMAGE
    # master.vm.box_version = BOX_VERSION
    master.vm.network :private_network, ip:"192.168.101.100"
    master.vm.network :forwarded_port, guest: 22, host: 21100, id: 'ssh'
    master.vm.hostname = 'master.local'
    master.vm.provision "shell", path: "src/scripts/setup.sh"
    master.vm.provider "virtualbox" do |v|
        v.memory = 3072
        v.cpus = 4
      end
  end

  # slave node
  config.vm.define "node01", autostart:false do |node|
    node.vm.box = BOX_IMAGE
    # node.vm.box_version = BOX_VERSION
    node.vm.network :private_network, ip:"192.168.101.101"
    node.vm.network :forwarded_port, guest: 22, host: 21101, id: 'ssh'
    node.vm.hostname = 'node01.local'
    node.vm.provision "shell", path: "src/scripts/setup.sh"
  end

  # slave node
  config.vm.define "node02", autostart:false do |node|
    node.vm.box = BOX_IMAGE
    # node.vm.box_version = BOX_VERSION
    node.vm.network :private_network, ip:"192.168.101.102"
    node.vm.network :forwarded_port, guest: 22, host: 21102, id: 'ssh'
    node.vm.hostname = 'node02.local'
    node.vm.provision "shell", path: "src/scripts/setup.sh"
  end
end

