apiVersion: v1
kind: Config
clusters:
- name: image-checker
  cluster:
    server: https://image-policy.example.com/policy
    certificate-authority: /etc/kubernetes/epconfig/external-cert.pem
contexts:
- context:
    cluster: image-checker
    user: api-server
  name: image-checker
current-context: image-checker
preferences: {}
users:
- name: api-server
  user:
    client-certificate: /etc/kubernetes/epconfig/apiserver-client-cert.pem
    client-key: /etc/kubernetes/epconfig/apiserver-client-key.pem
