apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-fast-storage
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        ssd: "true"
      containers:
        - name: nginx
          image: ghcr.io/hlesey/nginx:1.21.6
