apiVersion: apps/v1
kind: DaemonSet
metadata:
 name: monitoring
spec:
  selector:
    matchLabels:
      name: monitoring
  template:
    metadata:
      labels:
        name: monitoring
    spec:
      containers:
      - name: nginx-container
        image: ghcr.io/hlesey/nginx:1.27
        volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html/index.html
          readOnly: true
      volumes:
      - name: shared-data
        hostPath:
          path: /etc/hostname
