apiVersion: apps/v1 
kind: ReplicaSet
metadata:
  name: phippy-api-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: phippy
      app.kubernetes.io/component: api
      app.kubernetes.io/version: v2.0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: phippy
        app.kubernetes.io/component: api
        app.kubernetes.io/version: v2.0
    spec:
      containers:
      - name: phippy-api
        image: ghcr.io/hlesey/phippy-api:2.0
        env:
        - name: DB_HOST
          value: "phippy-db"
        - name: DB_PORT
          value: "6379"
        resources:
          limits:
            memory: "100Mi"
          requests:
            cpu: "100m"
            memory: "100Mi"
        ports:
        - name: http
          containerPort: 5000
        livenessProbe:
          httpGet:
            path: /livez
            port: http
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
