apiVersion: v1
kind: Service
metadata:
  name: phippy-api-v2
spec:
  selector:
    app: phippy-api
    version: v2.0
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
